### ISSUE TITLE
Use of wget for GPG file

### ISSUE THREAD

**Issue by bcnewlin** [threatstack/threatstack-puppet#10]
The recent 1.5.1 release changed to use wget for downloading the gpg key instead of allowing yum to do it via curl. The comments say it was due to issues with RHEL 6. 

This is fine in theory but since curl is required for yum it is installed on all systems with yum. Wget is not necessarily installed and no dependency was added to make sure that it is. So it immediately failed on my system which doesn't have wget installed.

**Comment by tmclaugh** [comment]
My fault and I knew exactly where the issue was.  I mistakenly used ensure_resource() to install `curl` instead of `wget`.

I'm going to cut a new release of the module shortly.  Working on getting all the config management modules in sync right now.

**Comment by bcnewlin** [comment]
Thanks for the quick response. Unfortunately, installing wget is tricky for me because our repos are tightly controlled. I'd like to revert to an older version of the module. Is there any way a tag can be added for 1.5.0 that i can reference?
