### ISSUE TITLE
Gemfile rest-client has Vulnerability

### ISSUE THREAD

**Issue by test-ncmd** [threatstack/threatstack-puppet#37]
Github Enterprise Security Alerts report Gemfile is using rest-client version < 1.8 has vulnerability. Please resolve.

**Comment by benpatterson** [comment]
Hi @test-ncmd we are taking a look at this dependency.... No clear timeline yet but wanted you to know we're having a looksee.

**Comment by rockpapergoat** [comment]
this was fixed recently and not actively used in the puppet code.
