### ISSUE TITLE
Package only installation

### ISSUE THREAD

**Issue by aparkinson** [threatstack/threatstack-puppet#8]
I'm trying to work out how to do a package only installation. We are using puppet to prepare machine images and don't want the agent to be configured until runtime

https://threatstack.zendesk.com/hc/en-us/articles/204289149-Steps-for-Deploying-the-Threat-Stack-Agent-via-Amazon-AMI-s

**Comment by tmclaugh** [comment]
How does a bool called $::threatstack::no_configure defaulted to `true` work for you?  Set it to `false` during image generation and if there's Puppet in use after a host comes up set it to `true`.  Would that work?

**Comment by aparkinson** [comment]
Yes, that would work

**Comment by tmclaugh** [comment]
@aparkinson want to try PR #9?  That should give you what you need.  If you like it I'll merge and update the other CM repos.

**Comment by aparkinson** [comment]
Thanks @tmclaugh
